services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  web:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://db:27017/paperiq_db
    depends_on:
      - db
volumes:
  mongo_data: